CREATE TABLE WEATHER_MEASUREMENT(
   ID BIGINT NOT NULL AUTO_INCREMENT,
   REMOTE_ID BIGINT,
   AMBIENT_TEMPERATURE DECIMAL(6,2) NOT NULL,
   AMBIENT_TEMPERATURE_HT DECIMAL(6,2),
   GROUND_TEMPERATURE DECIMAL(6,2) NOT NULL,
   AIR_QUALITY DECIMAL(6,2) NOT NULL,
   AIR_PRESSURE DECIMAL(6,2) NOT NULL,
   HUMIDITY DECIMAL(6,2) NOT NULL,
   WIND_DIRECTION DECIMAL(6,2) NULL,
   WIND_SPEED DECIMAL(6,2) NOT NULL,
   WIND_GUST_SPEED DECIMAL(6,2) NOT NULL,
   RAINFALL DECIMAL (6,2) NOT NULL,
   CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( ID ),
   KEY `created keys` (`CREATED`)
);
